[package]
name = "rote"
version = "0.1.0"
authors = ["coderstephen <me@stephencoakley.com>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
filetime = "0.1"
getopts = "0.2"
glob = "0.2"
lazysort = "0.1.0"
tar = "0.3.2"
term = "0.2"

[dependencies.lua]
git = "https://github.com/jcmoyer/rust-lua53"
