site_name: Rote
repo_url: https://github.com/coderstephen/rote
site_description: "The inspiringly simple taks runner and build tool."
site_author: "Stephen Coakley"
copyright: "&copy; Stephen Coakley"
pages:
- Home: index.md
- 'Getting Started': getting-started.md
- Examples: examples.md
theme: journal
