[package]
name = "sass"
version = "0.1.0"
authors = ["coderstephen <me@stephencoakley.com>"]

[lib]
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
sass-rs = { git = "https://github.com/compass-rs/sass-rs" }
