[package]
name = "script"
version = "0.1.0"
authors = ["coderstephen <me@stephencoakley.com>"]

[lib]
path = "lib.rs"

[dependencies]
filetime = "0.1"
log = "0.3"
lua = { git = "https://github.com/jcmoyer/rust-lua53" }
