[package]
name = "docker"
version = "0.1.0"
authors = ["coderstephen <me@stephencoakley.com>"]

[lib]
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
docker = "0.0.41"
runtime = { path = "../runtime" }
