[package]
name = "runtime"
version = "0.1.0"
authors = ["coderstephen <me@stephencoakley.com>"]

[lib]
path = "lib.rs"

[dependencies]
libc = "0.1"
lua = { git = "https://github.com/jcmoyer/rust-lua53" }
