[package]
name = "runtime"
version = "0.1.0"
authors = ["coderstephen <me@stephencoakley.com>"]

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[dependencies]
log = "0.3"
lua = { git = "https://github.com/jcmoyer/rust-lua53" }
